# Example configuration for OpenWebUI GitHub Connector
# Copy this file to config.yaml and update the values

log_level: info

# Sync schedule configuration
schedule:
  interval: 1h  # Options: 30m, 1h, 2h, 6h, 12h, 24h

# Local storage configuration
storage:
  path: /data  # Path where files will be stored locally

# OpenWebUI API configuration
openwebui:
  base_url: "http://localhost:8080"  # OpenWebUI instance URL
  api_key: ""  # Set via OPENWEBUI_API_KEY environment variable

# GitHub adapter configuration
github:
  enabled: true
  token: ""  # Set via GITHUB_TOKEN environment variable
  mappings:
    - repository: "owner/repo1"
      knowledge_id: "knowledge-base-1"
    - repository: "owner/repo2" 
      knowledge_id: "knowledge-base-2"
    - repository: "microsoft/vscode"
      knowledge_id: "vscode-knowledge-base"

# Confluence adapter configuration
confluence:
  enabled: false
  base_url: "https://your-domain.atlassian.net"  # Your Confluence instance URL
  username: "your-email@example.com"  # Your Confluence username (usually email)
  api_key: ""  # Set via CONFLUENCE_API_KEY environment variable
  
  # Space mappings (per-space knowledge IDs)
  space_mappings:
    - space_key: "SPACEKEY1"
      knowledge_id: "space1-knowledge-base"
    - space_key: "SPACEKEY2"
      knowledge_id: "space2-knowledge-base"
    - space_key: "DOCS"
      knowledge_id: "docs-knowledge-base"
  
  # Parent page mappings (per-parent-page knowledge IDs)
  parent_page_mappings:
    - parent_page_id: "3098214470"
      knowledge_id: "parent-page-knowledge-base"
    - parent_page_id: "1234567890"
      knowledge_id: "another-parent-page-knowledge-base"
  
  page_limit: 100  # Maximum pages to fetch per space (0 = no limit)
  include_attachments: true  # Whether to download and sync page attachments

# Local Folders adapter configuration
local_folders:
  enabled: false
  mappings:
    - folder_path: "/path/to/docs"
      knowledge_id: "docs-knowledge-base"
    - folder_path: "/path/to/guides"
      knowledge_id: "guides-knowledge-base"
    - folder_path: "/path/to/notes"
      knowledge_id: "notes-knowledge-base"

# Slack adapter configuration
slack:
  enabled: false
  token: ""  # Set via SLACK_TOKEN environment variable
  channel_mappings:
    - channel_id: "C1234567890"  # Slack channel ID
      channel_name: "general"     # Channel name for display
      knowledge_id: "general-knowledge-base"
    - channel_id: "C0987654321"
      channel_name: "dev-team"
      knowledge_id: "dev-knowledge-base"
    - channel_id: "C1122334455"
      channel_name: "support"
      knowledge_id: "support-knowledge-base"
  days_to_fetch: 30        # Number of days to fetch messages (default: 30)
  maintain_history: false  # Whether to maintain indefinite history or age off (default: false)
  message_limit: 1000      # Max messages per channel per run (default: 1000)
  include_threads: true    # Whether to include thread messages (default: true)
  include_reactions: false # Whether to include reaction data (default: false)

# Example configurations for different environments:

# Development
# log_level: debug
# schedule:
#   interval: 5m
# openwebui:
#   base_url: "http://localhost:8080"
#   api_key: "dev-api-key"
# confluence:
#   enabled: true
#   base_url: "https://dev-company.atlassian.net"
#   username: "dev-user@company.com"
#   api_key: "dev-confluence-api-key"
#   spaces:
#     - "DEV"
#   knowledge_id: "dev-knowledge-base-id"
#   page_limit: 50
#   include_attachments: false

# Production
# log_level: info
# schedule:
#   interval: 1h
# openwebui:
#   base_url: "https://openwebui.yourdomain.com"
#   api_key: "prod-api-key"
# confluence:
#   enabled: true
#   base_url: "https://company.atlassian.net"
#   username: "sync-bot@company.com"
#   api_key: "prod-confluence-api-key"
#   spaces:
#     - "DOCS"
#     - "WIKI"
#     - "PROJECTS"
#   knowledge_id: "prod-knowledge-base-id"
#   page_limit: 500
#   include_attachments: true

# Kubernetes (using environment variables)
# All values should be set via environment variables or ConfigMap
# log_level: info
# schedule:
#   interval: 1h
# storage:
#   path: /data
# openwebui:
#   base_url: ""  # Set via OPENWEBUI_BASE_URL
#   api_key: ""   # Set via OPENWEBUI_API_KEY
# github:
#   enabled: true
#   token: ""        # Set via GITHUB_TOKEN
#   repositories: [] # Set via ConfigMap
#   knowledge_id: "" # Set via GITHUB_KNOWLEDGE_ID
# confluence:
#   enabled: false
#   base_url: ""     # Set in ConfigMap
#   username: ""     # Set in ConfigMap
#   api_key: ""      # Set via CONFLUENCE_API_KEY
#   spaces: []       # Set in ConfigMap
#   knowledge_id: "" # Set in ConfigMap
#   page_limit: 100
#   include_attachments: true
