apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-config
  labels:
    app: openwebui-content-sync
data:
  config.yaml: |
    log_level: info
    schedule:
      interval: 1h
    storage:
      path: /data
    openwebui:
      base_url: "http://open-webui:8080"
    github:
      enabled: true
      token: ""
      mappings:
        - repository: "owner/repo1"
          knowledge_id: "repo1-knowledge-base"
        - repository: "owner/repo2"
          knowledge_id: "repo2-knowledge-base"
    confluence:
      enabled: false
      base_url: "https://your-domain.atlassian.net"
      username: "your-email@example.com"
      api_key: ""
      space_mappings:
        - space_key: "SPACEKEY1"
          knowledge_id: "space1-knowledge-base"
        - space_key: "SPACEKEY2"
          knowledge_id: "space2-knowledge-base"
      parent_page_mappings:
        - parent_page_id: "1234567890"
          knowledge_id: "parent-page-knowledge-base"
      page_limit: 100
      include_attachments: true
    local_folders:
      enabled: false
      mappings:
        - folder_path: "/data/docs"
          knowledge_id: "docs-knowledge-base"
        - folder_path: "/data/guides"
          knowledge_id: "guides-knowledge-base"
    slack:
      enabled: false
      token: ""
      channel_mappings:
        - channel_id: "C1234567890"
          channel_name: "general"
          knowledge_id: "general-knowledge-base"
        - channel_id: "C0987654321"
          channel_name: "dev-team"
          knowledge_id: "dev-knowledge-base"
      days_to_fetch: 30
      maintain_history: false
      message_limit: 1000
      include_threads: true
      include_reactions: false
